version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.0.0-sdk
    steps:
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Build
          command: |
             dotnet restore;
             dotnet build;
