version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.0.0-sdk
    steps:
      - checkout
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: BuildTest
          command: dotnet restore
